name = "BlockmodelUtils"
uuid = "d9f899e1-303a-530d-8675-c26bf1ea3f35"
authors = ["Jakob Hoffmann <jfb-hoffmann@homtail.de>"]
version = "0.1.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
BlockmodelsMakieExt = "Makie"

[compat]
BlockArrays = "1.4.0"
Graphs = "1.12.0"
IterTools = "1.10.0"
Makie = "0.22"
PrettyTables = "2.4.0"
julia = "1.10"
